### ISSUE TITLE
[날씨 컴포넌트 개선 제안]

### ISSUE THREAD

**Issue by C17AN** [Korea-Aerospace-University/KAUBOARD#17]
![image](https://user-images.githubusercontent.com/26535030/98541263-8680da00-22d2-11eb-88bd-8cfa7c51cdc3.png)

날씨 컴포넌트 프로토타입에 일부 문제가 있습니다.

1. **안예쁨**!! - 현재 색감... 공대생의 최선이라곤 하지만... 폰트랑 함께 수정이 시급합니다... ㅜㅜㅜ
(현재 폰트를 대체할 감각적인 폰트 제안도 받습니다!!)

2. 상단이 플렉스박스 레이아웃을 채택하고 있어 날씨 컴포넌트의 너비만큼 중앙 시계가 왼쪽으로 밀려나고 있습니다.
`position` 속성을 변경하던지, 어떻게든 중앙 시계를 가운데 정렬할 수 있도록..... ㅜㅜ

3. 서버로부터 날씨를 불러오는 동안 (약 1초 내외) 날씨 탭은 NAN 값만을 출력합니다.
데이터 로딩 중에 "로딩 중" 등 대체 텍스트를 볼 수 있게 해주세요!

4. 날씨 컴포넌트는 아직 완성되지 않았습니다.
날씨 부분에 커서를 올리면 이번 주 전체 날씨 정보도 표시할 수 있도록 보완하려 합니다!
(이번 주 날씨 정보는 https://calm-mesa-43659.herokuapp.com/weather 로 get 요청 보내면 얻을 수 있음)

**Comment by syj1198** [comment]
안녕하세요 :) 컴퓨터공학과에 재학 중인 공대생입니다!! 해당 Open Source에 기여해보고 싶습니다! 특별히 건드리지 말아야 할 부분은 따로 없나요?

**Comment by C17AN** [comment]
@syj1198 재학생이 아니더라도 코드를 사랑하시는 분이라면 누구든 가능합니다!!
단순히 색상 RGB값을 수정하는 것부터 새로운 컴포넌트를 작성하는 것까지 어떤 형태의 기여든 환영합니다!
(이슈 템플릿, 리드미 고도화, Contributing.md 작성 등... 어떤 형태의 기여든 열려 있습니다 😍)

혹시 Pull Request 방법을 잘 모르시거나, 더 궁금하신 내용이 있다면 편하게 issue 또는 메일 남겨주세요! 😄
프로젝트에 관심을 가져주셔서 감사드립니다 🙏

**Comment by C17AN** [comment]
안녕하세요!! 저희 프로젝트에 관심을 가져주셔서 진심으로 감사드립니다 😍
사실 구글 공유 스프레드시트 등으로 작업할 내용을 공유하면서 진행하면 좋은데... 아직은 정신이 없어서 코드 짜기에도 급급하네요! 😆

특별히 건드리지 말아야 할 부분은 딱히 없습니다!

대신 몇 가지 알아두시면 좋을 것 같은 내용이 있어 공유드립니다 🙏

1. 코드로 기여하실때 prettier 등의 플러그인으로 한 줄에 들어오는 코드가 80자 이내가 되도록 해주세요!
(코드 가독성을 위해서인데요, prettier 기본 설정으로 맞춰 놓으셔도 됩니다!)

2. 컴포넌트 내 요소에 클래스명을 지정할 때는 "컴포넌트명__역할" 이런 네이밍을 권장합니다!
(Ex. Subway 컴포넌트일 경우 -> <div className = "Subway__incoming">진입 중</div>)

3. 우선 이번 달은 날씨 컴포넌트만 완벽하게 완성하는 것이 목표인데요 (기말고사가 있는지라 🤣)
날씨 정보 API 서버 (헤로쿠 배포) URL : https://calm-mesa-43659.herokuapp.com/weather
(/GET 요청 사용)
혹시 필요하실 수도 있으실까봐 API 서버 주소도 남겨드립니다!

4. 기여분이 프로젝트에 반영되면 이렇게 조직 프로젝트에 기여했다는 멋진 마크가 생깁니다!
편하게 기여해주시고, 마크 받아 가세요! 😎
[image: image.png]

5. 그 외 궁금한 점이나, '이 부분 해도 될까' 싶으신 부분은 메일이나 이슈 남겨주시면 최대한 빨리 봐드릴게요!


2020년 11월 10일 (화) 오전 4:19, Hololo <notifications@github.com>님이 작성:

**Comment by C17AN** [comment]
4번 항목을 제외한 모든 항목 개선이 완료되어 이 이슈는 닫겠습니다.
